env | less

LC_PAPER=en_AU.UTF-8
XDG_VTNR=2
LC_ADDRESS=en_AU.UTF-8
SSH_AGENT_PID=2434
XDG_SESSION_ID=1
LC_MONETARY=en_AU.UTF-8
VTE_VERSION=4205
TERM=xterm-256color
SHELL=/bin/bash
XDG_MENU_PREFIX=gnome-
DERBY_HOME=/usr/lib/jvm/java-8-oracle/db
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
LC_NUMERIC=en_AU.UTF-8
WINDOWID=33554438
GTK_MODULES=gail:atk-bridge
USER=wrd
